name: master-merge
run-name: merging to master
on:
  push:
    branches:
      - main
jobs:
  cog_release_job:
    runs-on: ubuntu-latest
    name: Semver release
    steps:
      - uses: cocogitto/cocogitto-action@v3
        id: release
        with:
          release: true
          git-user: 'Cog Bot'
          git-user-email: 'mycoolproject@org.org'

      # The version number is accessible as a github action output
      - name: Print version
        run: "echo '${{ steps.release.outputs.version }}'"
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - run: docker buildx build . 
